### PR TITLE
some useful links for SNA with python (:

### PR DESCRIPTION
**Pull request by taniki**
links to:
- ipython notebooks/jupyter
- cyper
- python-louvain

### CODE REVIEW

**Comment by briatte** [comment]
Merged, thanks! I believe that's my first GitHub merge ever :)

**Comment by briatte** [comment]
P.S. Removed jupyter because it's not directly related to network analysis, but I've checked, it is (of course) listed in the Awesome Python list that is mentioned at the beginning of the Python subsection.

Have you taken a look at [this Google spreadsheet](https://docs.google.com/spreadsheets/d/1vJILk2EW1JnR3YAwTSSqAV5mPkeXaezy45wOoafBpfU/edit#gid=0)? It might contain other awesome Python network things.

I'm also closing #19 thanks to your PR.

**Comment by taniki** [comment]
Just did. Will get a look at networkit and spacy.io. I don't know if I am mainstream but I would add gensim (excellent library to perform Topic Modelling like Latent Dirichlet Allocation or Word2Vec) and scikit-learn without going ultra-deep into machine learning, there are good tools to build better visualization but also classifications and inferences over missing informations.

There is also some lib that add the dplyr syntax to python e.g. https://github.com/dodger487/dplython

**Comment by briatte** [comment]
I like very much all the Python stuff that you are mentioning. For this list, just make sure that all additions are about network analysis -- dplython, ggplot, jupyter, for instance, are all awesome, but should be in the Awesome Python list instead :)

**Comment by taniki** [comment]
yep, that was just to mention some stuffs that often appears in broad network analysis (: I was wondering if all stuffs related to specific programming languages won't overload the list.

**Comment by briatte** [comment]
The Software section is loooooong, but I believe it's very useful. We just need to trim it a bit – see #16  – at some point.

**Pull request merged**
