### PR TITLE
Added 2 machine learning on networks awesome lists.

### PR DESCRIPTION
**Pull request by benedekrozemberczki**

### CODE REVIEW

**Comment by shaylayonce** [comment]
Do you even

**Comment by benedekrozemberczki** [comment]
Care? Smile? Celebrate Christmas? Stop Working? K

**Comment by briatte** [comment]
@benedekrozemberczki Thanks very much for the commit! And for your patience. I'll add you to the bottom list of contributors, using your GitHub profile.

@shaylayonce ?

**Comment by briatte** [comment]
@benedekrozemberczki Done, added you to the contributors.

Also, you probably already know about this, but just in case: https://paperswithcode.com/

Thanks again!

**Pull request merged**
